/* GENERATED by editors/build-prism.ts — do not edit.
 * Source of truth: editors/tjs-syntax.ts
 */
export const tjs = {
  'doc-comment': {
    pattern: /\/\*#[\s\S]*?\*\//,
    greedy: true,
    alias: 'comment',
  },
  comment: {
    pattern: /\/\/.*|\/\*[\s\S]*?(?:\*\/|$)/,
    greedy: true,
  },
  forbidden: {
    pattern: /\b(?:var|eval)\b/,
    alias: 'important',
  },
  'block-construct': {
    pattern: /\b(?:test|mock|wasm|given|extend)\b(?=\s*(?:['"`]|\{))/,
    alias: 'keyword',
  },
  dangerous: {
    pattern: /\b(?:unsafe|DangerousLegacyEquals|DangerousLegacyNot|LegacyExactly|LegacyNotExactly|LegacyDefault)\b/,
    alias: 'important',
  },
  declaration: {
    pattern: /\b(?:Type|Generic|Enum|Union|FunctionPredicate|Exactly)\b/,
    alias: 'class-name',
  },
  'example-value': {
    pattern: /([a-zA-Z_$][a-zA-Z0-9_$]*)\s*:\s*('[^']*'|"[^"]*"|\d+|\{[^}]*\}|\[[^\]]*\]|true|false|null)/,
    inside: {
      parameter: /^[a-zA-Z_$][a-zA-Z0-9_$]*/,
      punctuation: /:/,
      value: { pattern: /[\s\S]+/, alias: 'string' },
    },
  },
  'return-type': {
    pattern: /\)\s*:[!?]?\s*(\{[^}]+\}|'[^']*'|"[^"]*"|\[[^\]]*\]|\w+)/,
    inside: {
      'safety-marker': { pattern: /[!?]/, alias: 'important' },
      punctuation: /[):]/,
      value: { pattern: /[\s\S]+/, alias: 'string' },
    },
  },
  'type-name': {
    pattern: /\b(?:int|unsigned|uint|float|number|string|boolean|bigint|object|any|unknown|void|never|null|undefined)\b/,
    alias: 'builtin',
  },
  string: {
    pattern: /(["'`])(?:\\[\s\S]|(?!\1)[^\\])*\1/,
    greedy: true,
  },
  'class-name': /\b(?:Date|Set|Map|Array|Object|String|Number|Boolean|RegExp|Error|JSON|Math|Schema|expect|assert|Timestamp|Exactly|Is|IsNot|Eq|NotEq|TypeOf)\b/,
  keyword: /\b(?:function|return|if|else|while|for|of|in|try|catch|finally|let|const|true|false|null|undefined|Type|Generic|Enum|Union|FunctionPredicate|predicate|example|description|declaration|extend|wasm|test|mock|unsafe|given|async|await|throw|import|export|class|extends|super|this|new|static|typeof|instanceof|delete)\b/,
  boolean: /\b(?:true|false)\b/,
  number: /\b0[xX][\da-fA-F]+\b|(?:\b\d+(?:\.\d*)?|\B\.\d+)(?:[eE][+-]?\d+)?/,
  operator: /[<>]=?|[!=]=?=?|--?|\+\+?|&&?|\|\|?|[?*/~^%]/,
  punctuation: /[{}[\];(),.:]/,
}

/* Register with a global Prism if one is present, so a <script> tag works too. */
if (typeof globalThis !== 'undefined' && globalThis.Prism) {
  globalThis.Prism.languages.tjs = tjs
}

export default tjs
