/**
 * Generates `src/vm/regex-folds.ts`: the case-insensitive equivalence classes the VM regex engine
 * uses for the `i` flag, with and without `u`.
 *
 * JavaScript's Canonicalize is not "compare upper and lower case": without `u` it is the
 * single-character uppercase except where that maps non-ASCII to ASCII; with `u` it is Unicode
 * simple case folding. Hand-written approximations missed titlecase digraphs (ǅ ~ Ǆ ~ ǆ), old
 * Cyrillic forms (ᲀ ~ в), Greek with tonos (ΐ ~ ΐ) and dotless ı. So the classes are DERIVED from
 * the host engine: two characters are equivalent exactly when `/x/i.test(y)`. Each probe is a
 * one-character literal pattern built here, so it cannot backtrack.
 *
 * `render()` is pure; the write happens only when this file is run directly. The committed
 * table is checked against a fresh `render()` by `src/vm/regex-folds.test.ts`, so a host whose
 * Unicode data moved fails a test rather than matching differently in silence.
 */
import { writeFileSync } from 'fs'
import { join } from 'path'
export { decodeFolds } from '../src/vm/regex'

const escape = (s: string) => s.replace(/[\\^$.*+?()[\]{}|/-]/g, '\\$&')

/** Equivalence classes with more than one member, each sorted, sorted by first member. */
export function foldClasses(unicode: boolean): number[][] {
  const max = unicode ? 0x10ffff : 0xffff
  const flags = unicode ? 'iu' : 'i'
  const str = (x: number) =>
    unicode ? String.fromCodePoint(x) : String.fromCharCode(x)
  // every character, indexed by its case mappings, so each one's candidate partners are found
  const byKey = new Map<string, number[]>()
  const add = (k: string, x: number) => {
    const a = byKey.get(k)
    if (a) a.push(x)
    else byKey.set(k, [x])
  }
  const skip = (x: number) => unicode && x >= 0xd800 && x <= 0xdfff
  for (let x = 0; x <= max; x++) {
    if (skip(x)) continue
    const s = str(x)
    add(s.toUpperCase(), x)
    add(s.toLowerCase(), x)
  }
  const parent = new Map<number, number>()
  const find = (x: number): number => {
    let r = x
    while (parent.has(r) && parent.get(r) !== r) r = parent.get(r)!
    return r
  }
  const union = (a: number, b: number) => {
    const ra = find(a)
    const rb = find(b)
    if (ra !== rb) parent.set(Math.max(ra, rb), Math.min(ra, rb))
    if (!parent.has(Math.min(ra, rb)))
      parent.set(Math.min(ra, rb), Math.min(ra, rb))
  }
  for (let c = 0; c <= max; c++) {
    if (skip(c)) continue
    const s = str(c)
    const u = s.toUpperCase()
    const l = s.toLowerCase()
    const cands = new Set<number>()
    for (const k of [s, u, l, u.toLowerCase(), l.toUpperCase()])
      for (const x of byKey.get(k) ?? []) if (x !== c) cands.add(x)
    if (!cands.size) continue
    const re = new RegExp(escape(s), flags)
    for (const d of cands) if (re.test(str(d))) union(c, d)
  }
  const classes = new Map<number, number[]>()
  for (const x of parent.keys()) {
    const r = find(x)
    const a = classes.get(r)
    if (a) a.push(x)
    else classes.set(r, [x])
  }
  return [...classes.values()]
    .filter((c) => c.length > 1)
    .map((c) => c.sort((a, b) => a - b))
    .sort((a, b) => a[0] - b[0])
}

/** Delta-encoded: each class's first member relative to the previous class's first, each
 * further member relative to the one before it, in base 36. Most classes are an adjacent pair. */
const encode = (classes: number[][]) => {
  let prev = 0
  return classes
    .map((c) => {
      const out = [c[0] - prev, ...c.slice(1).map((x, i) => x - c[i])]
      prev = c[0]
      return out.map((d) => d.toString(36)).join(',')
    })
    .join(';')
}

export function render(): string {
  return `/**
 * GENERATED by \`bun scripts/build-regex-folds.ts\` — never hand-edit. Case-insensitive
 * equivalence classes for the VM regex engine (\`i\` without and with \`u\`), derived from the host
 * engine's own Canonicalize; checked fresh by \`regex-folds.test.ts\`. Classes are separated by
 * \`;\`, members by \`,\`, as base-36 deltas (see \`encode\` in the script).
 */
export const FOLDS_I =
  '${encode(foldClasses(false))}'
export const FOLDS_IU =
  '${encode(foldClasses(true))}'
`
}

if (import.meta.main) {
  const out = join(import.meta.dir, '..', 'src', 'vm', 'regex-folds.ts')
  writeFileSync(out, render())
  console.log(`wrote ${out}`)
}
