/**
 * Tests that all playground examples transpile without errors
 *
 * Loads examples from demo/docs.json (generated by bin/docs.js)
 * to ensure they stay in sync with the actual playground.
 */

import { describe, test, expect } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import { tjs } from '../../src/lang'

// Load examples from docs.json
const docsPath = join(import.meta.dir, '../docs.json')
const docsJson = JSON.parse(readFileSync(docsPath, 'utf-8'))
const tjsExamples = docsJson.filter(
  (d: any) => d.type === 'example' && d.section === 'tjs' && d.code
)

describe('TJS Playground Examples', () => {
  for (const example of tjsExamples) {
    test(`"${example.title}" transpiles without error`, () => {
      expect(() => {
        tjs(example.code, { runTests: false })
      }).not.toThrow()
    })
  }
})

describe('TJS Playground Examples with tests', () => {
  // Examples that use imports can't run tests at transpile time
  const importExamples = new Set([
    'Date Formatting (with import)',
    'Local Module Imports',
    'Lodash Utilities (with import)',
    'Schema Validation', // imports tosijs-schema
    'React Todo (Comparison)', // comparison example, not runnable
    'tosijs Todo App', // requires tosijs runtime
    'Full-Stack Demo: Client App', // requires saved module
  ])

  for (const example of tjsExamples) {
    if (importExamples.has(example.title)) continue

    test(`"${example.title}" tests pass`, () => {
      const result = tjs(example.code, { runTests: 'report' })
      const failures = (result.testResults || []).filter((t: any) => !t.passed)
      if (failures.length > 0) {
        const msgs = failures.map((f: any) => `${f.description}: ${f.error}`)
        throw new Error(`Test failures:\n${msgs.join('\n')}`)
      }
    })
  }
})
