/**
 * Tests that all playground examples transpile without errors
 *
 * Loads examples from demo/docs.json (generated by bin/site.ts)
 * to ensure they stay in sync with the actual playground.
 */

import { describe, test, expect } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import { tjs } from '../../src/lang'
import { fromTS } from '../../src/lang/emitters/from-ts'
import { createRuntime, isMonadicError } from '../../src/lang/runtime'

// Load examples from docs.json
const docsPath = join(import.meta.dir, '../docs.json')
const docsJson = JSON.parse(readFileSync(docsPath, 'utf-8'))
const tjsExamples = docsJson.filter(
  (d: any) => d.type === 'example' && d.section === 'tjs' && d.code
)

describe('TJS Playground Examples', () => {
  for (const example of tjsExamples) {
    test(`"${example.title}" transpiles without error`, () => {
      expect(() => {
        tjs(example.code, { runTests: false })
      }).not.toThrow()
    })
  }
})

describe('TJS Playground Examples with tests', () => {
  // Examples that use imports can't run tests at transpile time
  const importExamples = new Set([
    'Date Formatting (with import)',
    'Local Module Imports',
    'Lodash Utilities (with import)',
    'Schema Validation', // imports tosijs-schema
    'React Todo (Comparison)', // comparison example, not runnable
    'tosijs Todo App', // requires tosijs runtime
    'Full-Stack Demo: Client App', // requires saved module
    'CDN Hints (overriding the default)', // imports tosijs and date-fns
    'Predicate Types', // imports tjs-lang/css
  ])

  for (const example of tjsExamples) {
    if (importExamples.has(example.title)) continue

    test(`"${example.title}" tests pass`, () => {
      const result = tjs(example.code, { runTests: 'report' })
      const failures = (result.testResults || []).filter((t: any) => !t.passed)
      if (failures.length > 0) {
        const msgs = failures.map((f: any) => `${f.description}: ${f.error}`)
        throw new Error(`Test failures:\n${msgs.join('\n')}`)
      }
    })
  }
})

/**
 * The examples' TOP-LEVEL CODE must actually run.
 *
 * The two gates above check that an example *transpiles*, and that its inline
 * `test { }` blocks pass. Neither executes the body — so an example with no inline
 * tests was never run at all, and that is most of them.
 *
 * `wasm-simd.md` shipped with its headline SIMD operation returning `undefined`: the
 * `wasm{}` block ended with a bare expression (`f32x4_extract_lane(acc, 0) + …`), i.e.
 * the author assumed Rust-style implicit last-expression return. TJS has no such rule,
 * so the block returned nothing. It compiled perfectly, had no inline tests, printed
 * `dot(...): undefined` against its own comment promising 2048, and nothing noticed.
 *
 * This runs the body and asserts two things a reader would notice immediately:
 * it doesn't throw, and it doesn't print `undefined`/`NaN` — the signature of a
 * computation that silently produced nothing.
 */
describe('TJS Playground Examples actually run', () => {
  /** Examples that cannot execute headlessly, and why. */
  const CANNOT_RUN: Record<string, string> = {
    Starfield: 'canvas + requestAnimationFrame animation loop',
    'Vector Search Benchmark': 'builds a results table in the DOM',
    'React Todo (Comparison)': 'React + DOM',
    'tosijs Todo App': 'requires the tosijs runtime and DOM',
    'CDN Hints (overriding the default)':
      'imports tosijs and date-fns from a CDN',
    'Date Formatting (with import)':
      'bare import, unresolvable in this harness',
    'Local Module Imports': 'imports a sibling module the playground provides',
    'Lodash Utilities (with import)':
      'bare import, unresolvable in this harness',
    'Schema Validation': 'imports tosijs-schema',
    'Full-Stack Demo: Client App':
      'requires a saved module from another example',
    'The Universal Endpoint': 'top-level import of a sibling module',
    'Using a WASM Library': 'top-level import of a sibling wasm module',
    'Predicate Types':
      'bare import of tjs-lang/css, unresolvable in this harness',
  }

  /** Examples whose OUTPUT legitimately contains undefined/NaN, and why. */
  const PRINTS_UNDEFINED: Record<string, string> = {
    'Honest Equality':
      'demonstrates `typeof undefined` and `null == undefined` — printing undefined IS the lesson',
  }

  const runnable = tjsExamples.filter((e: any) => !CANNOT_RUN[e.title])

  test('a majority of examples are actually runnable (guards a vacuous pass)', () => {
    // If the skip list ever grows to swallow everything, this gate stops meaning
    // anything — which is the failure mode skip lists have.
    expect(runnable.length).toBeGreaterThan(tjsExamples.length / 2)
  })

  for (const example of runnable) {
    test(`"${example.title}" runs and produces real values`, async () => {
      const { code } = tjs(example.code, { runTests: false })

      // `export` is meaningless in this harness and `new Function` rejects it; the
      // async IIFE carries the examples that use top-level await. Both are limits of
      // the harness, not properties of the example — worth adapting to rather than
      // adding to the skip list, since not running the body is the whole defect here.
      const body = code.replace(
        /^export\s+(?=(async\s+)?(function|const|let|var|class)\b)/gm,
        ''
      )

      const lines: string[] = []
      const realLog = console.log
      console.log = (...args: unknown[]) => {
        lines.push(args.map((a) => String(a)).join(' '))
      }
      try {
        await new Function(`return (async () => { ${body} })()`)()
      } finally {
        console.log = realLog
      }

      if (PRINTS_UNDEFINED[example.title]) return

      // A computation that silently produced nothing — what `dot()` printed.
      const empty = lines.filter((l) => /\b(undefined|NaN)\b/.test(l))
      expect(empty).toEqual([])
    })
  }
})

/**
 * The TypeScript examples RUN, and the ones that promise validation deliver it.
 *
 * They were only ever COMPILED (`demo/docs-fresh.test.ts`) — never executed — so three of them
 * could promise "invalid calls return error objects" and print `Hello, 42!`, and "The Full
 * Picture" could throw on its own bad-input demo. Behind that sat three defects in the
 * converter's pipeline: `TjsStrict` did not turn on validation, a `0.0` example narrowed to
 * integer, and interface examples spelled `any`, optional members and references to other
 * types in ways that rejected valid data (`src/lang/example-kinds.test.ts`).
 */
describe('TypeScript Playground Examples actually run', () => {
  const tsExamples = docsJson.filter(
    (d: any) => d.type === 'example' && d.section === 'ts' && d.code
  )

  /** Examples that demonstrate a REJECTION, and the line that must show it. */
  const MUST_REJECT: Record<string, RegExp> = {
    'Hello TypeScript': /^Bad call result:/,
    'Runtime Validation': /^divide\("ten", 2\) =/,
    'Object Validation': /^(String input|Wrong member type):/,
    'The Full Picture': /^Bad order:/,
  }

  test('apparatus: the TS examples are there, and the rejection list names real ones', () => {
    expect(tsExamples.length).toBeGreaterThan(10)
    const titles = new Set(tsExamples.map((e: any) => e.title))
    expect(Object.keys(MUST_REJECT).filter((t) => !titles.has(t))).toEqual([])
  })

  for (const example of tsExamples) {
    test(`"${example.title}" runs${
      MUST_REJECT[example.title] ? ', rejects its bad input' : ''
    }, and accepts its good input`, async () => {
      const js = tjs(fromTS(example.code, { emitTJS: true }).code, {
        runTests: false,
      }).code.replace(
        /^export\s+(?=(async\s+)?(function|const|let|var|class)\b)/gm,
        ''
      )
      const lines: { text: string; rejected: boolean }[] = []
      const realLog = console.log
      const saved = (globalThis as any).__tjs
      ;(globalThis as any).__tjs = createRuntime()
      console.log = (...args: unknown[]) => {
        lines.push({
          text: args.map((a) => String(a)).join(' '),
          rejected: args.some((a) => isMonadicError(a)),
        })
      }
      try {
        await new Function(`return (async () => { ${js} })()`)()
      } finally {
        console.log = realLog
        ;(globalThis as any).__tjs = saved
      }
      const pattern = MUST_REJECT[example.title]
      // A line that demonstrates a rejection must carry a MonadicError…
      const demo = lines.filter((l) => pattern?.test(l.text))
      if (pattern) {
        expect(demo.length).toBeGreaterThan(0)
        expect(demo.filter((l) => !l.rejected).map((l) => l.text)).toEqual([])
      }
      // …and no OTHER line may: valid input rejected is the defect this gate exists for.
      const wrongly = lines.filter((l) => l.rejected && !pattern?.test(l.text))
      expect(wrongly.map((l) => l.text)).toEqual([])
    })
  }
})
