/* tjs <- input.ts */

import { describe, it, expect } from 'bun:test'

import {
  defineAtom,
  isAgentError,
} from '/Users/tonioloewald/tjs-lang/src/runtime'

import { AgentVM } from '/Users/tonioloewald/tjs-lang/src/vm'

import { s } from 'tosijs-schema'

import { ajs } from '/Users/tonioloewald/tjs-lang/src/transpiler'

describe('Agent99 Runtime (VM)', () => {
  const vm = new AgentVM()
  it('should execute a manually constructed AST with ExprNode', async () => {
    const ast = {
      op: 'seq',
      steps: [
        {
          op: 'varSet',
          key: 'res',
          value: {
            $expr: 'binary',
            op: '+',
            left: { $expr: 'ident', name: 'val' },
            right: { $expr: 'literal', value: 10 },
          },
        },
        {
          op: 'return',
          schema: { type: 'object', properties: { res: { type: 'number' } } },
        },
      ],
    }
    const result = await vm.run(ast, { val: 5 })
    expect(result.result).toEqual({ res: 15 })
  })
  it('should run an AST generated by js() transpiler', async () => {
    const ast = ajs(`
      function calc({ price, tax }) {
        let total = price * (1 + tax)
        return { total }
      }
    `)
    const result = await vm.run(ast, { price: 100, tax: 0.2 })

    expect(result.result).toBeDefined()
    expect(result.result.total).toBe(120)
  })
  it('should handle complex math expressions using precedence', async () => {
    const ast = ajs(`
      function calc({ a, b, c }) {
        let res = (a + b) * c / 2
        return { res }
      }
    `)
    const result = await vm.run(ast, { a: 10, b: 20, c: 4 })
    expect(result.result.res).toBe(60)
  })
  it('should enforce fuel limits', async () => {
    const ast = {
      op: 'seq',
      steps: [
        { op: 'varSet', key: 'a', value: 1 },
        { op: 'varSet', key: 'b', value: 2 },
        { op: 'varSet', key: 'c', value: 3 },
      ],
    }

    const result = await vm.run(ast, {}, { fuel: 0.2 })
    expect(result.error).toBeDefined()
    expect(result.error?.message).toBe('Out of Fuel')
  })
  it('should return strict subsets of state based on schema', async () => {
    const ast = ajs(`
      function test() {
        let secret = 100
        let publicVal = 200
        return { publicVal }
      }
    `)
    const result = await vm.run(ast, {})
    expect(result.result.publicVal).toBe(200)
    expect(result.result.secret).toBeUndefined()
  })
  it('should enforce atom timeouts', async () => {
    const slowAtom = defineAtom(
      'testSlow',
      s.any,
      undefined,
      async () => {
        await new Promise((resolve) => setTimeout(resolve, 50))
      },
      { timeoutMs: 10 }
    )
    const vm = new AgentVM({ testSlow: slowAtom })
    const ast = {
      op: 'seq',
      steps: [{ op: 'testSlow' }],
    }
    const result = await vm.run(ast, {})
    expect(result.error).toBeDefined()
    expect(result.error?.message).toBe("Atom 'testSlow' timed out")
  })
  it('should set multiple variables with varsLet and compute expressions', async () => {
    const ast = ajs(`
      function test() {
        let a = 10
        let b = 20
        let c = "hello"
        let calcResult = a + b
        return { calcResult, a, c }
      }
    `)
    const result = await vm.run(ast, {})
    expect(result.result).toBeDefined()
    expect(result.result.calcResult).toBe(30)
    expect(result.result.a).toBe(10)
    expect(result.result.c).toBe('hello')
  })
  it('should generate a trace when trace mode is enabled', async () => {
    const ast = {
      op: 'seq',
      steps: [
        { op: 'varSet', key: 'x', value: 10 },
        {
          op: 'varSet',
          key: 'res',
          value: {
            $expr: 'binary',
            op: '+',
            left: { $expr: 'ident', name: 'x' },
            right: { $expr: 'ident', name: 'val' },
          },
        },
      ],
    }
    const { result, trace } = await vm.run(ast, { val: 5 }, { trace: true })
    expect(result).toBeUndefined()
    expect(trace).toBeDefined()
    if (!trace) throw new Error('Trace is undefined')
    expect(trace).toHaveLength(3)

    expect(trace[0].op).toBe('varSet')
    expect(trace[0].input).toEqual({ key: 'x', value: 10 })
    expect(trace[0].stateDiff).toEqual({ x: 10 })

    expect(trace[1].op).toBe('varSet')
    expect(trace[1].stateDiff).toEqual({ res: 15 })

    expect(trace[2].op).toBe('seq')

    expect(trace[2].stateDiff).toEqual({ x: 10, res: 15 })
  })
})

describe('Edge Cases', () => {
  const vm = new AgentVM()
  it('should handle division by zero (returns Infinity)', async () => {
    const ast = ajs(`
      function test({ n = 10 }) {
        let result = n / 0
        return { result }
      }
    `)
    const result = await vm.run(ast, { n: 10 })
    expect(result.result.result).toBe(Infinity)
    const result2 = await vm.run(ast, { n: -5 })
    expect(result2.result.result).toBe(-Infinity)
    const result3 = await vm.run(ast, { n: 0 })
    expect(Number.isNaN(result3.result.result)).toBe(true)
  })
  it('should handle zero fuel (immediate exhaustion)', async () => {
    const ast = ajs(`
      function test({ x = 1 }) {
        let y = x + 1
        return { y }
      }
    `)
    const result = await vm.run(ast, { x: 1 }, { fuel: 0 })
    expect(result.error).toBeDefined()
    expect(result.error?.message).toBe('Out of Fuel')
  })
  it('should handle unicode in state keys', async () => {
    const ast = ajs(`
      function test({ emoji = '🚀' }) {
        let result = emoji
        return { result }
      }
    `)
    const result = await vm.run(ast, { emoji: '🎉' })
    expect(result.result.result).toBe('🎉')
  })
  it('should handle nested try/catch', async () => {
    const ast = ajs(`
      function test({ shouldFail = false }) {
        let outerResult = 'initial'
        try {
          try {
            if (shouldFail) {
              outerResult = Error('inner error')
            }
            outerResult = 'inner success'
          } catch (innerErr) {
            outerResult = 'caught inner'
          }
        } catch (outerErr) {
          outerResult = 'caught outer'
        }
        return { outerResult }
      }
    `)
    const result = await vm.run(ast, { shouldFail: false })
    expect(result.result.outerResult).toBe('inner success')
  })
  it('should handle complex optional chaining', async () => {
    const ast = ajs(`
      function test({ obj = null }) {
        let a = obj?.level1?.level2?.value
        let b = obj?.missing?.also?.missing
        return { a, b }
      }
    `)

    const result1 = await vm.run(ast, { obj: null })
    expect(result1.result.a).toBeUndefined()
    expect(result1.result.b).toBeUndefined()

    const result2 = await vm.run(ast, {
      obj: { level1: { level2: { value: 42 } } },
    })
    expect(result2.result.a).toBe(42)
    expect(result2.result.b).toBeUndefined()
  })
  it('should handle deeply nested expressions', async () => {
    const ast = ajs(`
      function test({ x = 1 }) {
        let result = ((((x + 1) * 2) - 3) / 2) + 10
        return { result }
      }
    `)

    const result = await vm.run(ast, { x: 1 })
    expect(result.result.result).toBe(10.5)
  })
  it('should emit warning when using default in-memory store', async () => {
    const vm = new AgentVM()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'storeSet', key: 'test', value: 'hello' },
        { op: 'storeGet', key: 'test' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(ast, {})
    expect(result.warnings).toBeDefined()
    expect(result.warnings).toContain(
      'Using default in-memory store (not suitable for production)'
    )
  })
  it('should not emit store warning when custom store is provided', async () => {
    const vm = new AgentVM()
    const customStore = new Map()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'storeSet', key: 'test', value: 'hello' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(
      ast,
      {},
      {
        capabilities: {
          store: {
            get: async (key) => customStore.get(key),
            set: async (key, value) => {
              customStore.set(key, value)
            },
          },
        },
      }
    )
    expect(result.warnings).toBeUndefined()
  })
  it('should support console.warn in code', async () => {
    const vm = new AgentVM()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'consoleWarn', message: 'This is a warning' },
        { op: 'consoleWarn', message: 'Another warning' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(ast, {})
    expect(result.warnings).toBeDefined()
    expect(result.warnings).toContain('This is a warning')
    expect(result.warnings).toContain('Another warning')
  })
  it('should include console.warn in trace', async () => {
    const vm = new AgentVM()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'consoleWarn', message: 'traced warning' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(ast, {}, { trace: true })
    const warnEvent = result.trace?.find((e) => e.op === 'console.warn')
    expect(warnEvent).toBeDefined()
    expect(warnEvent?.input.message).toBe('traced warning')
  })
  it('should support console.log in trace', async () => {
    const vm = new AgentVM()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'consoleLog', message: 'debug message' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(ast, {}, { trace: true })
    const logEvent = result.trace?.find((e) => e.op === 'console.log')
    expect(logEvent).toBeDefined()
    expect(logEvent?.input.message).toBe('debug message')
  })
  it('should support console.error to stop execution', async () => {
    const vm = new AgentVM()
    const ast = {
      op: 'seq',
      steps: [
        { op: 'varSet', key: 'before', value: 'set' },
        { op: 'consoleError', message: 'Fatal error occurred' },
        { op: 'varSet', key: 'after', value: 'should not run' },
        { op: 'return', schema: {} },
      ],
    }
    const result = await vm.run(ast, {})
    expect(result.error).toBeDefined()
    expect(result.error?.message).toBe('Fatal error occurred')
  })
  it('should execute dynamically generated code with runCode', async () => {
    const vm = new AgentVM()

    const ast = ajs(`
      function dynamicExec({ multiplier = 3 }) {
        let code = 'function calc() { let x = 5 * 7; return { result: x } }'
        let output = runCode({ code, args: {} })
        let final = output.result * multiplier
        return { dynamicResult: output.result, final }
      }
    `)

    const { transpile } = await import(
      '/Users/tonioloewald/tjs-lang/src/transpiler'
    )
    const result = await vm.run(
      ast,
      { multiplier: 2 },
      {
        capabilities: {
          code: {
            transpile: (source) => transpile(source).ast,
          },
        },
      }
    )
    expect(result.result.dynamicResult).toBe(35)
    expect(result.result.final).toBe(70)
  })
  it('should share fuel budget between parent and runCode', async () => {
    const vm = new AgentVM()

    const ast = ajs(`
      function fuelTest() {
        let code = 'function loop() { let i = 0; while (i < 100) { i = i + 1 }; return { count: i } }'
        let output = runCode({ code, args: {} })
        return { result: output.count }
      }
    `)
    const { transpile } = await import(
      '/Users/tonioloewald/tjs-lang/src/transpiler'
    )
    const result = await vm.run(
      ast,
      {},
      {
        fuel: 500,
        capabilities: {
          code: {
            transpile: (source) => transpile(source).ast,
          },
        },
      }
    )
    expect(result.result.result).toBe(100)

    expect(result.fuelUsed).toBeGreaterThan(10)
  })
  it('should fail gracefully when code.transpile capability is missing', async () => {
    const vm = new AgentVM()
    const ast = ajs(`
      function noCapability() {
        let output = runCode({ code: 'function x() { return { y: 1 } }', args: {} })
        return { output }
      }
    `)
    const result = await vm.run(
      ast,
      {},
      {
        capabilities: {},
      }
    )
    expect(result.error).toBeDefined()
    expect(result.error?.message).toContain('code.transpile')
  })
  it('should transpile code without executing via transpileCode', async () => {
    const vm = new AgentVM()
    const ast = ajs(`
      function getAst() {
        let code = 'function add(a: 1, b: 2) { return { sum: a + b } }'
        let ast = transpileCode({ code })
        return { ast }
      }
    `)
    const { transpile } = await import(
      '/Users/tonioloewald/tjs-lang/src/transpiler'
    )
    const result = await vm.run(
      ast,
      {},
      {
        capabilities: {
          code: {
            transpile: (source) => transpile(source).ast,
          },
        },
      }
    )
    expect(result.result.ast).toBeDefined()
    expect(result.result.ast.op).toBe('seq')
    expect(result.result.ast.steps).toBeDefined()
  })
  it('should limit runCode recursion depth', async () => {
    const vm = new AgentVM()

    const ast = ajs(`
      function recursiveCode() {
        let code = 'function inner() { let x = runCode({ code: "function f() { return { v: 1 } }", args: {} }); return { x } }'
        let result = runCode({ code, args: {} })
        return { result }
      }
    `)
    const { transpile } = await import(
      '/Users/tonioloewald/tjs-lang/src/transpiler'
    )

    const result = await vm.run(
      ast,
      {},
      {
        capabilities: {
          code: {
            transpile: (source) => transpile(source).ast,
          },
        },
      }
    )

    expect(result.result.result.x.v).toBe(1)
  })
  it('should validate atom output against outputSchema', async () => {
    const badAtom = defineAtom(
      'badOutput',
      s.object({}),
      s.object({ value: s.number }),
      async () => {
        return { value: 'not a number' }
      }
    )
    const vm = new AgentVM({ badOutput: badAtom })
    const ast = {
      op: 'seq',
      steps: [{ op: 'badOutput', result: 'res' }],
    }
    const result = await vm.run(ast, {})

    expect(result.error).toBeDefined()
    expect(result.error?.message).toContain('Output validation failed')
    expect(result.error?.op).toBe('badOutput')
  })
  it('should allow valid atom output that matches outputSchema', async () => {
    const goodAtom = defineAtom(
      'goodOutput',
      s.object({}),
      s.object({ value: s.number }),
      async () => {
        return { value: 42 }
      }
    )
    const vm = new AgentVM({ goodOutput: goodAtom })
    const ast = {
      op: 'seq',
      steps: [
        { op: 'goodOutput', result: 'res' },
        {
          op: 'return',
          schema: { type: 'object', properties: { res: { type: 'object' } } },
        },
      ],
    }
    const result = await vm.run(ast, {})

    expect(result.error).toBeUndefined()
    expect(result.result.res).toEqual({ value: 42 })
  })
  describe('footgun-free equality in expressions (== is NOT structural)', () => {
    it('distinct arrays are NOT equal (== matches TJS, not structural)', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '==',
              left: { $expr: 'literal', value: [1, 2, 3] },
              right: { $expr: 'literal', value: [1, 2, 3] },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(false)
    })
    it('distinct objects are NOT equal (== matches TJS, not structural)', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '==',
              left: { $expr: 'literal', value: { a: 1, b: 2 } },
              right: { $expr: 'literal', value: { a: 1, b: 2 } },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(false)
    })
    it('== does not coerce types', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '==',
              left: { $expr: 'literal', value: '1' },
              right: { $expr: 'literal', value: 1 },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(false)
    })
    it('!= returns true for distinct objects', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '!=',
              left: { $expr: 'literal', value: { a: 1 } },
              right: { $expr: 'literal', value: { a: 2 } },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(true)
    })
    it('null == undefined is true (nullish equality)', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '==',
              left: { $expr: 'literal', value: null },
              right: { $expr: 'ident', name: 'missing' },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(true)
    })
    it('=== still uses identity comparison', async () => {
      const ast = {
        op: 'seq',
        steps: [
          {
            op: 'varSet',
            key: 'res',
            value: {
              $expr: 'binary',
              op: '===',
              left: { $expr: 'literal', value: [1, 2] },
              right: { $expr: 'literal', value: [1, 2] },
            },
          },
          {
            op: 'return',
            schema: {
              type: 'object',
              properties: { res: { type: 'boolean' } },
            },
          },
        ],
      }
      const result = await vm.run(ast, {})
      expect(result.result.res).toBe(false)
    })
  })
  describe('strict object returns', () => {
    it('should allow object returns', async () => {
      const ast = ajs(`function test() { return { value: 42 } }`)
      const result = await vm.run(ast, {})
      expect(result.result).toEqual({ value: 42 })
      expect(result.error).toBeUndefined()
    })
    it('should allow empty object returns', async () => {
      const ast = ajs(`function test() { return {} }`)
      const result = await vm.run(ast, {})
      expect(result.result).toEqual({})
      expect(result.error).toBeUndefined()
    })
    it('should allow bare return (no value)', async () => {
      const ast = {
        op: 'seq',
        steps: [{ op: 'return', value: undefined }],
      }
      const result = await vm.run(ast, {})
      expect(result.error).toBeUndefined()
    })
    it('should allow null return', async () => {
      const ast = {
        op: 'seq',
        steps: [{ op: 'return', value: null }],
      }
      const result = await vm.run(ast, {})
      expect(result.error).toBeUndefined()
    })
    it('should reject number return', async () => {
      const ast = {
        op: 'seq',
        steps: [{ op: 'return', value: { $expr: 'literal', value: 42 } }],
      }
      const result = await vm.run(ast, {})
      expect(isAgentError(result.result)).toBe(true)
      expect(result.error?.message).toContain('must return an object')
      expect(result.error?.message).toContain('number')
    })
    it('should reject string return', async () => {
      const ast = {
        op: 'seq',
        steps: [{ op: 'return', value: { $expr: 'literal', value: 'hello' } }],
      }
      const result = await vm.run(ast, {})
      expect(isAgentError(result.result)).toBe(true)
      expect(result.error?.message).toContain('must return an object')
      expect(result.error?.message).toContain('string')
    })
    it('should reject array return', async () => {
      const ast = {
        op: 'seq',
        steps: [
          { op: 'return', value: { $expr: 'literal', value: [1, 2, 3] } },
        ],
      }
      const result = await vm.run(ast, {})
      expect(isAgentError(result.result)).toBe(true)
      expect(result.error?.message).toContain('must return an object')
      expect(result.error?.message).toContain('array')
    })
    it('should reject boolean return', async () => {
      const ast = {
        op: 'seq',
        steps: [{ op: 'return', value: { $expr: 'literal', value: true } }],
      }
      const result = await vm.run(ast, {})
      expect(isAgentError(result.result)).toBe(true)
      expect(result.error?.message).toContain('must return an object')
      expect(result.error?.message).toContain('boolean')
    })
    it('should allow AgentError to propagate through return', async () => {
      const ast = ajs(`
        function test({ x }) {
          if (x < 0) {
            return { error: 'negative' }
          }
          return { value: x }
        }
      `)
      const result = await vm.run(ast, { x: -1 })
      expect(result.result).toEqual({ error: 'negative' })
      expect(result.error).toBeUndefined()
    })
  })
})
